### ISSUE TITLE
Repository final refactor

### ISSUE THREAD

**Issue by jeanchilger** [JeanCHilger/SCAL#45]
**Due Date:** 20/07/2020

In order to remove the "Refactor in Progress" status, this repository will need to accomplish the following:

- [x] **a.** Remove temporary (and runtime generated) files from repository; add then to `.gitignore` (**PR** #47);
- [x] **b.** Gather all utility files (e.g. `handle_errors`) into a single directory (**PR** #48);
- [x] **c.** Delete all unused files (like `doAll_Baseline_4gram`) (**PR** #49);
- [x] **d.** Rename files to match conventions, as in issue #9 (**PR** #50);
- [x] **e.** Refactor remaining code to match conventions, as in issue #9 (**PR** #51):
  - [x] *i.* `script_prune_pairs.sh`;
  - [x] *ii.* `script_select_pairs.sh`;
  - [x] *iii.* `dosteminline`;
  - [x] *iv.* `dofeaturesseed`;
  - [x] *v.* `Corpus/dofast`;
- [ ] **f.** Update master branch with wrongly placed changes, then delete unused and outdated branches;

**Note:** `SSARP` won't be refactored for now.
